#!/usr/bin/env bash
# A Bash script that runs an infinite loop and handles the SIGTERM signal to prevent termination.
# The trap command catches SIGTERM (signal 15) and executes the specified echo command.
trap 'echo "I am invincible!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 1
done
