#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using the SIGKILL (signal 9) signal.
# SIGKILL is a forceful signal that a process cannot ignore.
kill -9 "$(pgrep -f 7-highlander)"
