#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a for loop.

# We use '_' as the variable name to show it's intentionally unused and
# avoid the ShellCheck SC2034 warning.
for _ in {1..10}; do
  echo "Best School"
done
