#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a for loop.

# The 'for' loop will iterate 10 times.
# {1..10} is a sequence expression that generates numbers from 1 to 10.
for i in {1..10}; do
  echo "Best School"
done
